server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://43.143.100.58:3306/blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: alin
    password: HEZ3caw2i7eJNzby
    driver-class-name: com.mysql.cj.jdbc.Driver
      #配置获取连接等待超时的时间
    maxWait: 60000
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为loaclhost）
    host: 43.143.100.58
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password: pjl2000726
    # redis连接超时时间（单位毫秒）
    timeout: 5000
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

